#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with  and , the first  terms will be: By considering the terms in the Fibonacci
#sequence whose values do not exceed four million, find the sum of the even-valued terms.

a, b = 1, 2

even_sum = 0

while a <= 4000000:
    if a % 2 == 0:   # Check if the number is even
        even_sum += a
    
    # Generate next Fibonacci number
    a, b = b, a + b

print("Sum of even Fibonacci numbers:", even_sum)